### ISSUE TITLE
Make addition in 'makefile'

### ISSUE THREAD

**Issue by gHuwk** [YoungMeatBoy/findme#1]
During installation, the PATH must be checked for the pip.exe installer. Is it possible to call the installer to immediately add it to the PATH directory? Thank you .

**Comment by YoungMeatBoy** [comment]
Makefile here just a shortcut of the installation with `pip`.  It'll not be fixed. Install `pip` or change makefile by yourself. Send a pull request and if it's correct - I'll accept it.
